[project]
name = "mysite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aratinga",
    "ruff>=0.6.5",
]

[tool.uv.sources]
aratinga = { git = "https://github.com/roraimae/aratinga" }