[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64"]

[project]
name = "aratinga"
description = "Wagtail + Voreios Extensions enabling rapid development of brasilian public educational-focused websites."
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Fabio Santos", email = "fabio@voreios.com.br"}
]

dynamic = ["version"]
license = {file = "LICENSE.txt"}
dependencies = [
    "django>=4.2.16",
    "django-govbrds",
    
]

[project.scripts]
aratinga = "aratinga.bin.aratinga:main"

[tool.setuptools]
packages = ["aratinga"]

[tool.setuptools.dynamic]
version = {attr = "aratinga.__version__"}

[tool.uv.sources]
django-govbrds = { git = "https://github.com/roraimae/django-govbrds.git" }
