# Generated by Django 6.0.3 on 2026-03-19 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aratingaadmin', '0006_themesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aratingaadmin.theme', verbose_name='Active theme'),
        ),
    ]
