# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from datetime import datetime

# Add the project root to the path
sys.path.insert(0, os.path.abspath('../src'))

# -- Project information -------------------------------------------------------

project = 'Aratinga CMS'
copyright = f'{datetime.now().year}, Aratinga Contributors'
author = 'Aratinga Contributors'

# The short X.Y version
version = '1.0'
# The full version, including alpha/beta/rc tags
release = '1.0.0'

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (and others just as third party ones).
extensions = [
    'sphinx.ext.autodoc',           # Auto-document from docstrings
    'sphinx.ext.intersphinx',       # Link to other projects' docs
    'sphinx.ext.viewcode',          # Add links to source code
    'sphinx.ext.imgmath',           # Math equation rendering
    'myst_parser',                  # Markdown support
    'sphinx_tabs.tabs',             # Tabbed content
    'sphinxext.opengraph',          # OpenGraph meta tags
]

# Add any paths that contains templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that shouldn't be included
# when building the documentation. This also includes files containing a
# substitution references, wildcards patterns or suffixes that should not be
# included in the archive.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you sell translated versions of your documentation
# under the "Powered by Sphinx" link. If you don't want to link to Sphinx,
# you can set this to an empty string.
language = 'en'

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the theme
# documentation for more information about changing the theme and its
# parameters.
html_theme = 'furo'

# Theme options are theme-specific and used by html_theme_path above
html_theme_options = {
    'light_css_variables': {
        'color-brand-primary': '#17a2b8',
        'color-brand-content': '#17a2b8',
        'color-problematic': '#b3950b',
    },
    'footer_icons': [
        {
            'name': 'GitHub',
            'url': 'https://github.com/f4biosa/aratinga',
            'html': '''
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                </svg>
            ''',
        },
    ],
}

# Add any paths that contains custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom CSS
html_css_files = [
    'custom.css',
]

# Output file base name for HTML help builder.
htmlhelp_basename = 'AratingaCMS'

# HTML logo
html_logo = '_static/aratinga-logo.svg'

# Favicon
html_favicon = '_static/favicon.ico'

# Show the "Show source" button
html_show_sourcelink = True

# -- Options for LaTeX output -------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4',

    # The font size for LaTeX ('10pt', '11pt', '12pt').
    'pointsize': '11pt',

    # Additional preamble that doesn't use document.conf_py_c_content_markup
    'preamble': r'''
\usepackage{charter}
\usepackage[defaultsans]{lato}
\usepackage{inconsolata}
''',
}

# Grouping the document tree into LaTeX files. If there are multiple files
# that you want to compile into separate PDF files, list them all here.
# If not '', a string will be inserted as \chapter*{#1} and \chapter{#2}
# before and after an item.
latex_documents = [
    (master_doc, 'AratingaCMS.tex', 'Aratinga CMS Documentation',
     'Aratinga Contributors', 'manual'),
]

# -- Options for manual page output -------------------------------------------

# One entry per manual page. List of tuples (source start file, name, description
# listed in the manual, authors, manual section).
man_pages = [
    (master_doc, 'aratinga', 'Aratinga CMS Documentation',
     [author], 1)
]

# -- Options for Texinfo output -----------------------------------------------

# Grouping the document tree into Texinfo files. If there are multiple files
# that you want to compile into separate PDF files, list them all here.
# If not '', a string will be inserted as \chapter*{#1} and \chapter{#2}
# before and after an item.
texinfo_documents = [
    (master_doc, 'AratingaCMS', 'Aratinga CMS Documentation',
     author, 'AratingaCMS', 'A powerful, flexible open-source CMS built on Django and Wagtail',
     'Miscellaneous'),
]

# -- Options for Epub output --------------------------------------------------

# Bibliographic Dublin Core metadata names.
epub_metadata = {
    'language': 'en',
}

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_uid = ''

# A unique identification for the text.
#
# epub_id = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# -- Options for intersphinx --------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'django': ('https://docs.djangoproject.com/en/stable/', 'https://docs.djangoproject.com/en/stable/_objects/'),
    'wagtail': ('https://docs.wagtail.io/en/stable/', None),
}

# -- Options for autodoc -----------------------------------------------------

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'show-inheritance': True,
    'inherited-members': True,
}

autoclass_content = 'both'

# -- Options for sphinx_tabs --------------------------------------------------

sphinx_tabs_disable_tab_closing = True

# -- Options for OpenGraph ---------------------------------------------------

ogp_social_cards = {
    "enable": False
}

ogp_site_url = "https://aratinga.readthedocs.io/"
ogp_site_name = "Aratinga CMS Documentation"
ogp_image = "https://aratinga.readthedocs.io/_static/aratinga-logo.svg"
ogp_image_alt = "Aratinga CMS Logo"
ogp_description_length = 200
ogp_type = "website"
ogp_type_article = "article"

# -- Custom configuration for MyST (Markdown) --------------------------------

myst_enable_extensions = [
    "colon_fence",  # Enable ::: for note directives
    "deflist",      # Enable definition lists
    "dollarmath",   # Enable math with $ syntax
    "fieldlist",    # Enable field lists
    "linkify",      # Auto-detect URLs
    "smartquotes",  # Enable smart quotes
    "substitution", # Enable substitutions
    "tasklist",     # Enable checklists
]

myst_heading_anchors = 3

# -- Custom event handlers ---------------------------------------------------

def setup(app):
    """Setup Sphinx application."""
    # Add custom event handlers here if needed
    pass
